### ISSUE TITLE
bug in slice

### ISSUE THREAD

**Issue by SuHui** [hashbangCoder/Neural-Conversational-Model#1]
can you help me fix this bug?

Start Training...
Saving final checkpoint...Model saved at : Checkpoints/
Halting Queues and Threads
Traceback (most recent call last):
  File "chatbot.py", line 137, in <module>
    train(options)
  File "chatbot.py", line 118, in train
    _,batch_loss,train_step,summary= sess.run([train_op,mean_loss,global_step,merged])
  File "/soft/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 717, in run
    run_metadata_ptr)
  File "/soft/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 915, in _run
    feed_dict_string, options, run_metadata)
  File "/soft/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 965, in _do_run
    target_list, options, run_metadata)
  File "/soft/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 985, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.InvalidArgumentError: indices[0,0] = 49506 is not in [0, 49506)
     [[Node: embedding_lookup_1 = Gather[Tindices=DT_INT64, Tparams=DT_DOUBLE, _class=["loc:@embed_vecs"], validate_indices=true, _device="/job:localhost/replica:0/task:0/cpu:0"](embed_vecs/read, batch:1)]]
Caused by op u'embedding_lookup_1', defined at:
  File "chatbot.py", line 137, in <module>
    train(options)
  File "chatbot.py", line 65, in train
    decoder_batch = tf.cast(embedding_ops.embedding_lookup(embedding,mini_batch[1]),tf.float32)
  File "/soft/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/embedding_ops.py", line 86, in embedding_lookup
    validate_indices=validate_indices)
  File "/soft/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 988, in gather
    validate_indices=validate_indices, name=name)
  File "/soft/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 703, in apply_op
    op_def=op_def)
  File "/soft/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2334, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/soft/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1253, in __init__
    self._traceback = _extract_stack()

**Comment by hashbangCoder** [comment]
Hey sorry about the late response. Have you resolved it? 
There have been a couple of changes to the tensorflow api in the embedding_ops, python.ops submodule etc. I am running v0.11 and have not been able to recreate your error.

**Comment by YinJerry** [comment]
I met the same problem as SuHui and I also changed my tensorflow version from v0.12 to v0.11 but it does not work. 
Suhui, have you solved your problem? 
Thank you!
